name: flutter_microduino_html_example
description: Demonstrates how to use the flutter_microduino_html plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_microduino_html:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/asset/static/
    - assets/mEditorLatexBlockPlugin/static/fonts/
    - assets/microduinoAsset/static/
    - assets/static/blocks-media/
    - assets/static/blocks-media/extensions/
    - assets/static/blocks-media/icons/
    - assets/static/chrome/
    - assets/static/css/
    - assets/static/fonts/
    - assets/static/groot/hex/
    - assets/static/images/account/
    - assets/static/images/assetInfo/
    - assets/static/images/banner/
    - assets/static/images/comment/
    - assets/static/images/device/
    - assets/static/images/doc/
    - assets/static/images/grootMenuBar/
    - assets/static/images/header/
    - assets/static/images/homeIcon/
    - assets/static/images/icons/
    - assets/static/images/mode/
    - assets/static/images/school/
    - assets/static/img/
    - assets/static/js/
    - assets/static/mdesigner/
    - assets/static/
    - assets/vmAsset/static/drums/
    - assets/vmAsset/static/instruments/1-piano/
    - assets/vmAsset/static/instruments/2-electric-piano/
    - assets/vmAsset/static/instruments/3-organ/
    - assets/vmAsset/static/instruments/4-guitar/
    - assets/vmAsset/static/instruments/5-electric-guitar/
    - assets/vmAsset/static/instruments/6-bass/
    - assets/vmAsset/static/instruments/7-pizzicato/
    - assets/vmAsset/static/instruments/8-cello/
    - assets/vmAsset/static/instruments/9-trombone/
    - assets/vmAsset/static/instruments/10-clarinet/
    - assets/vmAsset/static/instruments/11-saxophone/
    - assets/vmAsset/static/instruments/12-flute/
    - assets/vmAsset/static/instruments/13-wooden-flute/
    - assets/vmAsset/static/instruments/14-bassoon/
    - assets/vmAsset/static/instruments/15-choir/
    - assets/vmAsset/static/instruments/16-vibraphone/
    - assets/vmAsset/static/instruments/17-music-box/
    - assets/vmAsset/static/instruments/18-steel-drum/
    - assets/vmAsset/static/instruments/19-marimba/
    - assets/vmAsset/static/instruments/20-synth-lead/
    - assets/vmAsset/static/instruments/21-synth-pad/
    - assets/extension-worker.js
    - assets/favicon.ico
    - assets/index.html
    - assets/react-loadable.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
